### ISSUE TITLE
질문 겸 이슈입니다.

### ISSUE THREAD

**Issue by jicjjang** [appkr/l5essential#11]
## 좋은 강좌 감사합니다 :)

순서대로 따라해보다가 13-restful-resource-controller.md에서 TokenMismatchException 부분을 따라해보고 있습니다.
#### 간단한... 이슈

제일 아래 부분에 "POST http://localhost:8000/posts가 정상 동작하는 것을 확인한 후, 이번에는 POST http://localhost:8000/posts/1 으로 요청해 보자." 라고 써놓으셨는데 /posts/1 은 위에 php artisan route:list CLI 명령어를 보시면 POST가 없네요.
#### 질문

그리고 POST http://localhost:8000/posts는 정상 동작하는데, 이 부분에서 막혀야 하는게 아닌가... 궁금하네요.  POST 방식으로 http://localhost:8000/posts 이 경로로 데이터를 포함해서 보내는데 csrf 오류가 나야하지 않는지...

**Comment by appkr** [comment]
@jicjjang 안녕하세요? 질문 고맙습니다.
1. `POST http://localhost:8000/posts/1` 부분은 제 설명이 부족했던 것 같습니다. MethodNotAllowed 를 설명하기 위한 내용이었습니다. 문제를 발생시키고, 문제 발생원인과 해결방안을 설명하는 방식으로 강좌를 진행하는 것이 제 방식입니다. 내용을 보강해 놓겠습니다.
2. `$except = ['posts', 'posts/*'];` 처리를 하기 전에 `POST http://localhost:8000/posts` 요청을 했는데, CSRF 예외가 발생하지 않았다는 말씀이시죠? 사용하시는 라라벨 버전을 알려 주시면 확인해 보도록 하겠습니다. `$ artisan --version` 으로 확인하시면 됩니다.

고맙습니다.

**Comment by jicjjang** [comment]
버전은 5.2.6입니다 :)

**Comment by appkr** [comment]
@jicjjang [#10](https://github.com/appkr/l5essential/issues/10) 이랑 관련이 있을 듯 하네요. `VerifyCsrfToken` 미들웨어가 `web` 이란 Route Group 으로 묶이면서, 해당 미들웨어를 타지 않을 가능성이 있습니다. 확인하시고, 해결 되면 다시 한번 상태 업데이트 부탁드릴게요.

**Comment by jicjjang** [comment]
`$except = ['posts', 'posts/*'];` 처리를 하기 전, 후 POST http://localhost:8000/posts 요청을 해도, CSRF 예외가 발생하지 않았습니다.... ㅠㅠ
물론, #10 을 참고해서  `Route::group(['middleware' => ['web']], function () { ... }` 안에 Route 정의를 다 넣었습니다.

**Comment by appkr** [comment]
@jicjjang 증상을 한번 보고 싶은 데, 계신데가 어디시죠? 서울이라면 언제든 괜찮으니, 20 분 정도 시간 내 주세요. 제 메일 juwonkim@me.com 으로 연락 주세요.

**Comment by jicjjang** [comment]
<img width="626" alt="2016-02-22 3 30 20" src="https://cloud.githubusercontent.com/assets/6022539/13211152/4c0d3bcc-d979-11e5-91d3-9e303588666f.png">

제대로 해결되었습니다. 제가 이해를 제대로 못했었네요 ㅠㅠ... RouteGroup 처리한 것으로 제대로 동작했습니다.
도움 감사합니다.
