### ISSUE TITLE
20강 이슈가 있습니다

### ISSUE THREAD

**Issue by jicjjang** [appkr/l5essential#12]
<img width="846" alt="2016-02-24 3 16 59" src="https://cloud.githubusercontent.com/assets/6022539/13277126/c3321b8c-db09-11e5-9a49-1f027475556e.png">

20강 위 사진과 같은 부분에서 "Missing argument 2" 에러가 발생합니다.
$bindings와 $time 없이 아래와 같이 해주니 잘 돌아갑니다 :)

```
DB::listen(function($sql) {
    var_dump($sql);
});
```

**Comment by appkr** [comment]
@jicjjang 지적 고맙습니다. 라라벨 5.2 부터는 모든 코어 이벤트가 이벤트 데이터로 객체를 던지게 바뀌었습니다. 해서 위 코드는 

``` php
DB::listen(function ($event) {
    var_dump($event->sql);
    // var_dump($event->bindings);
    // var_dump($event->time);
});
```

처럼 바뀌어야 합니다. 반영해 놓도록 하겠습니다.
