### ISSUE TITLE
7강 오타가 있습니다.

### ISSUE THREAD

**Issue by jongguheo** [appkr/l5essential#13]
마스터 레이아웃 사용하기의 하단 내용에 오타가 있었습니다.

![exam](https://cloud.githubusercontent.com/assets/16233937/13804323/588c8466-eb8f-11e5-9a3d-6e3ffa3ecc68.png)

이 부분에서, 내용과 같이 index.php로 파일명을 하여 실행하면

[@extends('master') @section('content') Your Content here!! @stop] 이렇게 결과가 나왔습니다.

파일명을 index.blade.php로 수정하여 실행하자,

[Your content here!! ] 이라는 정상적인 결과가 나왔습니다:)

**Comment by appkr** [comment]
@jongguheo 신고 고맙습니다. 예 맞습니다. 곧 수정하도록 하겠습니다.
