### ISSUE TITLE
06-blade-101.md - 오탈자 및 양식 오류

### ISSUE THREAD

**Issue by desty** [appkr/l5essential#14]
- 오탈자
  와 같이 HTML 주석으로 컴파일 된다. 그럼데 브라우저에서 소스보기로 보면 엄연히 다르다
  ->
  와 같이 HTML 주석으로 컴파일 된다. 그런데 브라우저에서 소스보기로 보면 엄연히 다르다
- 양식오류
  {{-- --}} - Comment
  의 html 소스 부분에 오류가 있어서 인지 아래 @foreach와 겹쳐진거 같습니다.

**Comment by appkr** [comment]
고맙습니다. 반영하겠습니다.
