### ISSUE TITLE
저장시 관계 문제

### ISSUE THREAD

**Issue by corean** [appkr/l5essential#18]
좋은 글 감사합니다.
현재 포럼  [ArticleController](https://github.com/appkr/l5essential/blob/master/lessons/37-articles.md)를 하던중 
`$article = Article::create($request->all());`
데이타 베이스 관계관련 에러가 나오네요. 
아마 author_id의 입력때문인것 같은데요.

`$article = new Article();`
        `$article->title = $request->input('title');`
        `$article->content = $request->input('content');`
        `$article->notification = $request->input('notification');`
        `$article->author_id = \Auth::id();`
        `$article->save();`
이렇게 해서 오류를 피했습니다.
혹시 다른 부분(모델등)에서 빼놓은게 있을까요?

**Comment by appkr** [comment]
``` php
$article = auth()->user()->articles()->create($request->all());

// 또는 

$article = \Auth::user()->articles()->create($request->all());
```

로 해보세요. 

정확한 커밋 해시의 코드 라인 번호를 몰라 제가 놓친 것인지, @corean 님이 놓친 부분이 있는 지 모르겠습니다. 해 보시고 결과 알려주세요.

**Comment by corean** [comment]
네 알려주신 코드로 잘 작동됩니다.

완성본 코드: https://github.com/appkr/l5essential/blob/master/app/Http/Controllers/ArticlesController.php#L86
여기에는 변경이 되어 있습니다.

강좌내용:
https://github.com/appkr/l5essential/blob/master/lessons/37-articles.md

**Comment by appkr** [comment]
예 이것도 역시 뒤로 가면서 하나씩 잡아 가는 부분입니다.
