### ISSUE TITLE
show.blade.php

### ISSUE THREAD

**Issue by corean** [appkr/l5essential#19]
비로그인 상태로 
http://forum.dev/articles/21 이런식으로 show.blade.php를 열게되면 
`Call to a member function isAdmin() on null` 오류가 있습니다.

`auth()->user()->isAdmin()`에서 사용자가 없기 때문일까요?

완성코드로는
https://github.com/appkr/l5essential/blob/master/resources/views/articles/show.blade.php#L39

**Comment by appkr** [comment]
기억이 가물합니다. 몇 장인지 모르겠는데, 뒤로 진행하면서 하나씩 잡아 나갈겁니다.
