### ISSUE TITLE
tag 입력값 없을때 sync()오류

### ISSUE THREAD

**Issue by corean** [appkr/l5essential#20]
https://github.com/appkr/l5essential/blob/master/app/Http/Controllers/ArticlesController.php#L87

입력받을때 tag를 선택을 안하면 저장할때 오류가 나와서
`Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatSyncList() must be of the type array, null given, called`

`$article->tags()->sync($request->input('tags'));`에 if문을 추가하였습니다.

`if ($request->input('tags')) {`
`$article->tags()->sync($request->input('tags'));`
`}`

**Comment by appkr** [comment]
예 잘하셨네요. 아마 뒤에서 유효성 검사하지 싶습니다. 태그가 없으면 컨트롤러에 도달하기도 전에 이전 입력 폼으로 되돌아가게...
