### ISSUE TITLE
27강 - Document 컨트롤러 View 오류의 건

### ISSUE THREAD

**Issue by smartyunhui** [appkr/l5essential#3]
좋은강좌 잘 보고 있습니다~ ^^

27강에서 뷰 생성시 블레이드 코드가 잘못 된 듯 해서 글 남깁니다.
resources/views/documents/index.blade.php

{{ $index }} -> {!! $index !!}
{{ $content }} -> {!! $content !!}

이렇게 {!! !!} 로 처리를 해야하지 않나요? 저는 학습하면서 {{ }} 로는 텍스트로 인식이되어 위와 같이 변경을 해서 처리했습니다.

**Comment by appkr** [comment]
@smartyunhui 예 맞습니다. 코드에는 `{!! !!}` 문법을 써 놓고, 문서에는 잘 못 써 놓았네요. 다음 번 푸쉬할 때 고쳐놓도록 하겠습니다. 고맙습니다.
